<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>bundleUUID</key>
	<string>3ea5de57-bce6-48cd-af64-a6e74db4da3d</string>
	<key>comment</key>
	<string>
	Caliper GISDK Language Definition for Sublime Text
	</string>
	<key>fileTypes</key>
	<array>
		<string>rsc</string>
		<string>gisdk</string>
		<string>model</string>
		<string>scenarios</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?i:(class|dbox|macro|toolbar|menu))\s+(\"[^\"]+\")</string>
	<key>foldingStopMarker</key>
	<string>(?i:(endclass|endmacro|enddbox|enditem|endmenu))\s*$</string>
	<key>keyEquivalent</key>
	<string>^~P</string>
	<key>name</key>
	<string>GISDK</string>
	<key>patterns</key>
		<array>
		<dict>
			<key>begin</key>
			<string>(?:^\s*)(?i:static|)(\s*)(?i:(Class))\s+(\"([a-zA-Z_][^\"]*)\")</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.GISDK</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.GISDK</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?:^\s*)(?i:(endClass))</string>
			<key>name</key>
			<string>meta.class.GISDK</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#init</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:^\s*)(?i:static|)(\s*)(?i:(DBox))\s+(\"([a-zA-Z_][^\"]*)\")</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.dbox.GISDK</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.dbox.GISDK</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?:^\s*)(?i:(endDBox))</string>
			<key>name</key>
			<string>meta.dbox.GISDK</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#init</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#widgets</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:^\s*)(?i:static|)(\s*)(?i:(Menu))\s+(\"([a-zA-Z_][^\"]*)\")</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.menu.GISDK</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.menu.GISDK</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?:^\s*)(?i:(endMenu))</string>
			<key>name</key>
			<string>meta.menu.GISDK</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#init</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#widgets</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:^\s*)(?i:static|)(\s*)(?i:(Toolbar))\s+(\"([a-zA-Z_][^\"]*)\")</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.toolbar.GISDK</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.toolbar.GISDK</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?:^\s*)(?i:(endToolbar))</string>
			<key>name</key>
			<string>meta.toolbar.GISDK</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#init</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#widgets</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#macro</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.GISDK</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.GISDK</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.GISDK</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.GISDK</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?&gt;\\\s*\n)</string>
							<key>name</key>
							<string>punctuation.separator.continuation.GISDK</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>widgets</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?:^\s*)((?i:(radio button|sample button|button|tab list|scroll list|dotnetcontrol|menu item|menuitem|tab|frame|text|edit text|edit integer|edit real|grid view|radio list|list|radio list|radio button|label|drop down|popdown menu|menu|tool|checkbox|sample|popdown|tree view|spinner|com control|dotnet control|tool))\s+\"[a-zA-Z_\-][^\"]*\")</string>
					<key>name</key>
					<string>entity.name.resource.GISDK</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.resource.GISDK</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#init</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#language</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>init</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?:^\s*)((?i:(init|close|update|done))?\s+(?i:do))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.macro.GISDK</string>
						</dict>
						<!--
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.init.GISDK</string>
						</dict>
						-->
					</dict>
					<key>end</key>
					<string>\b(?i:(endItem))\b</string>
					<key>name</key>
					<string>meta.init.GISDK</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#language</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>language</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#misc</string>
				</dict>
			</array>
		</dict>
		<key>dboxitem</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?:^\s*)(?i:static|)(\s*)(?i:(Macro))\s+(\"([a-zA-Z_\-][^\"]*)\")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.macro.GISDK</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.macro.GISDK</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\b(?i:(endMacro|endItem))\b</string>
					<key>name</key>
					<string>meta.macro.GISDK</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#language</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>macro</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?:^\s*)(?i:static|)(\s*)(?i:(Macro))\s+(\"([a-zA-Z_\-][^\"]*)\")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.macro.GISDK</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.macro.GISDK</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\b(?i:(endMacro|endItem))\b</string>
					<key>name</key>
					<string>meta.function.GISDK</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#language</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>misc</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.GISDK</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.GISDK</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.GISDK</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.GISDK</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:(true|false|separator|null|self|notfound|error|languageerror|escape|return|height|width|left|right|top|bottom|macro|class|dbox))\b</string>
					<key>name</key>
					<string>constant.language.source.GISDK</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.modifier.global.GISDK</string>
					</dict>
					</dict>
					<key>match</key>
					<string>\b(?i:(global|init|on|shared|static|default|same|after|docked|docking|dim|done|update|close|cancel|editable|readonly|disabled|do|end|enditem|endmacro|enddbox|endmenu|macro|dbox|toolbar|toolbox|class))\b</string>
				</dict>
				<dict>
					<key>match</key>
					<string>-?(?:0|[1-9]\d*)(?:\.\d+(?:[eE][+-]?\d+)?)?</string>
					<key>name</key>
					<string>constant.numeric.GISDK</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s*([a-zA-Z0-9_]+\:)\s*$</string>
					<key>name</key>
					<string>constant.literal.GISDK</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(docked|[A-Za-z]+)\:\s+(?=[^\s])</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
						<key>name</key>
						<string>entity.other.attribute-name.source.GISDK</string>
						</dict>
					</dict>
				</dict>
				<dict>
				<key>comment</key>
				<string>keywords that delimit flow blocks or alter flow from within a block</string>
				<key>match</key>
				<string>\b(else if|else|except|finally|for|if|try|then|to|while|goto|break|continue|return|yield)\b</string>
				<key>name</key>
				<string>keyword.control.flow.GISDK</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>keyword operators that evaluate to True or False</string>
					<key>match</key>
					<string>\b(in|and|not|or|\||\|\||&amp;|&amp;&amp;)\b</string>
					<key>name</key>
					<string>keyword.operator.logical.GISDK</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;&gt;|&lt;\=|&gt;\=|\=\=|&lt;|&gt;|\!\=</string>
					<key>name</key>
					<string>keyword.operator.comparison.GISDK</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\+\=|-\=|\*\=|/\=|//\=|%\=|&amp;\=|\|\=|\^\=|&gt;&gt;\=|&lt;&lt;\=|\*\*\=</string>
					<key>name</key>
					<string>keyword.operator.assignment.augmented.GISDK</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\+|\-|\*|\*\*|/|//|%|&lt;&lt;|&gt;&gt;|&amp;|\||\^|~</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.GISDK</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;\=</string>
					<key>name</key>
					<string>keyword.operator.assignment.GISDK</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.GISDK</string>
	<key>uuid</key>
	<string>3ea5de57-bce6-48cd-af64-a6e74db4da3d</string>
</dict>
</plist>
